module.exports = {
  important: false,
  corePlugins: [
    'padding',
    'margin',
    'textAlign',
    'textColor',
    'backgroundColor',
    'backgroundRepeat',
    'width',
    'height',
    'borderWidth',
    'borderStyle',
    'borderRadius',
    'borderColor',
    'cursor',
    'display',
    'flex',
    'flexWrap',
    'flexDirection',
    'justifyContent',
    'justifyItems',
    'justifySelf',
    'alignItems',
  ],
  theme: {
    spacing: {
      '0': '0',
      '0.5': '4px',
      '1': '8px',
      '2': '16px',
      '3': '24px',
      '4': '32px',
      '5': '40px',
      '6': '48px',
      '8': '64px',
    },
  },
  variants: {
    padding: [],
    margin: [],
    textAlign: [],
    width: [],
    height: [],
    backgroundColor: ['hover'],
    backgroundRepeat: [],
    textColor: ['hover'],
    borderWidth: [],
    borderColor: [],
    borderStyle: [],
    borderRadius: ['hover'],
    cursor: ['hover'],
    display: [],
    flex: [],
    flexWrap: [],
    flexDirection: [],
    justifyContent: [],
    justifyItems: [],
    justifySelf: [],
    alignItems: [],
  },
};
